### ISSUE TITLE
Is the label "None" used in the training of classifier?

### ISSUE THREAD

**Issue by bluesy7585** [ahmetgunduz/Real-time-GesRec#101]
Hi all,
I see label "None" in the annotation file (eg. egogestureall.json)

for classifier training, does it use "None" class for no gesture?
making total number of class + 1 for the model to predict
eg. egoGesture dataset has 83 classes, with additional "None" label, it will be 84 classes

**Comment by ahmetgunduz** [comment]
yes that is right
