### ISSUE TITLE
Training on the jester dataset - questions

### ISSUE THREAD

**Issue by olgapeled** [ahmetgunduz/Real-time-GesRec#14]
Hi,

I have some question regarding the training process:

1. Do you trained separability the two models? detection & classification
2. Can I use the jester dataset to train the two models? (something that confuses me is that one of the classes in the jester dataset is 'no gesture'? 
3. As I understand you used the same code in the main.py to train separability the two models?
4. If so, what do I need to change to switch between the training of the two models? excepts the network parameters? 

Thank you,
Olga

**Comment by ahmetgunduz** [comment]
Hi @olgapeled ,

**1. and 3.**
Yes, you have to first train you models (detector and classifier) in offline and then if you want you can evaluate in online (real time). And yes, `main.py` script will be used through `run_online.sh` by providing necessary parameters, which brings up the 4th question. 

**2.**
Sure you can do that. For detector, you will need two classes (`gesture` and `no_gesture`).  This will be a binary task. And for the classifier you will add all classes where there is a gesture.  Please see this issue for more details https://github.com/ahmetgunduz/Real-time-GesRec/issues/9#issuecomment-484380755

**4.**
what differs for classifier and detector is the number of classes, which is also a model parameter, and the input files under `annotation_Jester`. You will need to create a separate `classInd.txt`, `testlist01.txt`, `trainlist01.txt`, and `vallist01.txt` for detector and classifier. At the end, you will use these files to create two separate `.json` files. For example for EgoGesture they are named as `egogesturebinary.json` for detector and `egogestureall_but_None.json`.  You may see dataset preparation files under `utils/`. Unfortunately I do not have for Jester dataset but you may do a pull request if you would like to contribute. 

Best,
Ahmet

**Comment by olgapeled** [comment]
Great!!! Thank you very much!!!!

**Comment by nainadhingra2012** [comment]
Hi, I am using Jester dataset. I want to know what all changes are needed to be made for it. I have changed no. of classes to 27. I want to know of some other extra changes are needed?
I get error in   Jester.py
                                      def __getitem__(self, index): 
                                             im_dim = clip[0].size()[-2:]
                                              IndexError: list index out of range

when I print the len(clip), it gives 0.
 
I assume that the data is loaded properly.
any suggestions on how to solve it?

**Comment by ahmetgunduz** [comment]
Hi @nainadhingra2012 , 
If you are training and testing offline, following steps  in README and some changes in run_offline.sh should work. But it seems id did not load the data properly as it is giving the error. Better to check the data path.

**Comment by nainadhingra2012** [comment]
@ahmetgunduz, I double checked the data paths. They seem to be fine. I think you are right that the data is not loaded properly. But I am not getting what is getting wrong. Did you have any other suggestions?
I am using no. of frames =16

**Comment by nainadhingra2012** [comment]
Hi @ahmetgunduz, I found my problem. Thanks anyways.

I was using wrong modality for the data.

**Comment by ahmetgunduz** [comment]
👍
