### ISSUE TITLE
How to feed input to classifier in online_test.py using tensor.float

### ISSUE THREAD

**Issue by sathiez** [ahmetgunduz/Real-time-GesRec#20]
Hi, 
How to feed input to classifier in `online_test.py` using tensor.float .
I tried ,

`frame= np.reshape(frame,(1,1,1,512,512))
frame=cv2.normalize(frame,None,alpha=0,beta=1,norm_type=cv2.NORM_MINMAX,dtype=cv2.CV_32F)`
`input_clf = torch.from_numpy(frame).float()`
`outputs_det = classifier(inputs_clf)`

I get the following error,

`RuntimeError: invalid argument 2: input image (T: 1 H: 32 W: 16) smaller than kernel size (kT: 2 kH: 3 kW: 3) at /pytorch/aten/src/THCUNN/generic/VolumetricAveragePooling.cu:57`

_Originally posted by @sathiez in https://github.com/ahmetgunduz/Real-time-GesRec/issues/17#issuecomment-492933337_

**Comment by ahmetgunduz** [comment]
Hi @sathiez ,

This isrelated with your image dimentions. The networks accept images of size `112 x 112`; however, you input size is `512 x 512`. Could you please scale the image to 112. Except that, your code seems ok. 
Best,
Ahmet

**Comment by sathiez** [comment]
Hi Ahmet,
Thank you for your reply, when I change the image size to`112 * 112` I get the following error,
`RuntimeError: invalid argument 2: input image (T: 1 H: 4 W: 4) smaller than kernel size (kT: 2 kH: 3 kW: 3) at /pytorch/aten/src/THCUNN/generic/VolumetricAveragePooling.cu:57`. 

How can I resolve this error?

**Comment by ahmetgunduz** [comment]
It seems that the modality channel is lower than expected after conv operation. Are you feeding RGB or Depth images? `modality_clf` parameter in `online_test.sh` should be specified. "RGB"| "Depth" | "RGB-D"

**Comment by ahmetgunduz** [comment]
@sathiez , any update here. I will close the issue if it is solved.
