### ISSUE TITLE
NvGesture dataset

### ISSUE THREAD

**Issue by nainadhingra2012** [ahmetgunduz/Real-time-GesRec#22]
There are 31 files named:

                          nvGesture_v1.7z.001
                         to nvGesture_v1.7z.031
I am looking to extract these files to video format. Since these files are zipped in .7z format. I tried using

                          cat nvGesture_v1.7z.0?? | 7za x
or

                          cat nvGesture_v1.7z.0?? | 7za e
but in both cases I get error:

                            Error:
                            Incorrect command line

**Comment by nainadhingra2012** [comment]
I solved the issue :)

**Comment by LLLLLLoki** [comment]
How did you solve the problem? could you help me?i got the same error

**Comment by terasakisatoshi** [comment]
I'm trying to extract dataset but fails...

`7z`, `unar` does not solve my problem

**Comment by terasakisatoshi** [comment]
Solved 

`brew cask install the-unarchiver`

Then open directory you stored dataset 

select all files `nvGestreu_v1.7z00x` for x = 1,2,...,31. and right click button to go `open with unarchiver`. See the following image.

![image](https://user-images.githubusercontent.com/16760547/73366097-b7b68d80-42f0-11ea-9f53-9b176b87d214.png)

you'll get `nvGesture_v1.7z`.

Finally open `nvGesture_v1.7z` with `unarchiver`.

Done.

**Comment by ttrungtin** [comment]
> I solved the issue :)

Could you please let me know how you have solved it? Thanks in advance!!

**Comment by giangnd1808** [comment]
> I solved the issue :)

cái địt con bà mày ???

**Comment by terasakisatoshi** [comment]
I can't remember exactly, but this [StackOverflow link](https://askubuntu.com/questions/134227/how-to-extract-files-from-a-split-7zip-archive) saves your life? For example:

@giangnd1808 

```
$ apt-get install p7zip # gives 7z command below
$ cd /path/to/dir/nvGesture_v1.7z.001
$ 7z x nvGesture_v1.7z.001 -tsplit
```

**Comment by ganjbakhshali** [comment]
just remember to install the full version of 7z


`$ sudo apt-get install p7zip-full `

then extract will work
