### ISSUE TITLE
RGB-D result

### ISSUE THREAD

**Issue by 0x10cxR1** [ahmetgunduz/Real-time-GesRec#23]
Hi,

from the paper, I only saw RGB or Depth results, how about RGB-D? Are you able to release the pre-trained RGB-D models?

Thanks.

**Comment by okankop** [comment]
Which fusion type are you particularly interested in? We have investigated data level fusion for the models, which result in slightly better performance. We believe that feature or decision level fusions would increase the performance, but this would increase the memory footprint of the models two times and runtime would be two times slower. This is the reason why we are avoiding these type of fusions for real time applications.

**Comment by ahmetgunduz** [comment]
@0x10cxR1 , please check my thesis repo for RGB-D results. https://github.com/ahmetgunduz/TUM_Thesis
