### ISSUE TITLE
RGB pre-trained models

### ISSUE THREAD

**Issue by ABesginow** [ahmetgunduz/Real-time-GesRec#25]
Are the models in the drive also usable for RGB prediction/classification?

If not, could I kindly ask you to upload these models as well?

I am asking since the names would suggest that every model (except the jester) is for Depth data.

Thank you very much

**Comment by ahmetgunduz** [comment]
Hi, 
For RGB modality, unfortunatelly you have to train yourself, and you can use pretrained Jester mdoel as an initializer. But I should mention that depth modality models were always better in terms of performance. 
You are right, we only kept only the  depth modality models, the ones have highest performance score. 

I would double check if we still have the RGB modality models. If so I would upload them as well. 
Best,
Ahmet

**Comment by ABesginow** [comment]
Thanks very much.

I managed to use the jester as pretrained and train the RGB myself, so I guess you don't need to upload for me anymore. 

Closing and thanks for the Software btw. :)

**Comment by ahmetgunduz** [comment]
great!

**Comment by khasmamad99** [comment]
@ABesginow did you train a **detector** model for RGB input? As far as I understand, an RGB classifier trained on Jester is already available (jester_resnext_101_RGB_32.pth), but there is no RGB detector. If you have a trained model for RGB **detection** can you please share it?
