### ISSUE TITLE
ResNet Detector Model

### ISSUE THREAD

**Issue by Shaotran** [ahmetgunduz/Real-time-GesRec#28]
Hi Ahmet,

Could you quickly send the .PTH file for the ResNet10 Detector model you talk about in your paper? This would help with replicating what you did in your paper a lot! Thanks!

**Comment by ahmetgunduz** [comment]
Unfortunately, I do not have that model anymore only the ones in the drive link (a lighter version, namely ResNetL would work the same way, and it can be found in the link). Otherwise, you have to train it yourself.

**Comment by Shaotran** [comment]
Yikes. In that case, do you have the ResNetL model for the Jester dataset?

**Comment by ahmetgunduz** [comment]
No, but that is a pretty light model should be trained pretty fast even for jester.
