### ISSUE TITLE
Torch size error with Jester Dataset

### ISSUE THREAD

**Issue by parkjh688** [ahmetgunduz/Real-time-GesRec#31]
Hi.
I got this error message with Jester Dataset.

![Screenshot from 2019-08-02 15-44-12](https://user-images.githubusercontent.com/36429399/62350056-81b07080-b53c-11e9-943f-b818cd5baad5.png)

I don't know the second number's meaning of `torch.Size([64, 3, 7, 7, 7])` or `torch.Size([64, 1, 7, 7, 7])`.

and this is my run_offline.sh file.
```
#!/bin/bash
python main.py \
        --root_path ~/ \
        --video_path /home/eden/20BN-jester/20bn-jester-v1/videos \
        --annotation_path ~/Real-time-GesRec/annotation_Jester/jester.json\
        --result_path ~/Real-time-GesRec/results \
        --resume_path ~/Real-time-GesRec/jester_resnext_101_RGB_32.pth \
        --dataset jester \
        --sample_duration 8 \
    --learning_rate 0.01 \
    --model resnext \
        --model_depth 101 \
        --resnet_shortcut A \
        --batch_size 16 \
        --n_classes 27 \
        --n_finetune_classes 27 \
        --n_threads 16 \
        --checkpoint 1 \
        --modality Depth \
        --train_crop random \
        --n_val_samples 3 \
        --test_subset test \
     --n_epochs 100 \

```

**Comment by ahmetgunduz** [comment]
hi @parkjh688 ,

You are trying to load a RGB model with modality Depth. PLease ser `--modality RGB`

**Comment by parkjh688** [comment]
Hi Thanks for your help.
Could you tell me the third argument also?

**Comment by ahmetgunduz** [comment]
What do you meant by third argument? 

For the error can you try changing parameters to this method as 
https://github.com/ahmetgunduz/Real-time-GesRec/blob/cec7050b3cea2d3ec33967a1552d2022b89d4166/model.py#L115-L117

`
model = _modify_first_conv_layer(model,3,7)
`

**Comment by parkjh688** [comment]
I changed it but still have same error.

**Comment by parkjh688** [comment]
I changed 72 line code like this.

```
 70        if opt.modality == 'RGB' and opt.model != 'c3d':
 71             print("[INFO]: RGB model is used for init model")
 72             model = _modify_first_conv_layer(model, 7, 3) ##### Check models trained (3,7,7) or (7,7,7)
```

And I solve the error what I said, but I got this error.

	Unexpected key(s) in state_dict: "module.layer1.0.downsample.0.weight", "module.layer1.0.downsample.1.weight", "module.layer1.0.downsample.1.bias", "module.layer1.0.downsample.1.running_mean", "module.layer1.0.downsample.1.running_var", "module.layer2.0.downsample.0.weight", "module.layer2.0.downsample.1.weight", "module.layer2.0.downsample.1.bias", "module.layer2.0.downsample.1.running_mean", "module.layer2.0.downsample.1.running_var", "module.layer3.0.downsample.0.weight", "module.layer3.0.downsample.1.weight", "module.layer3.0.downsample.1.bias", "module.layer3.0.downsample.1.running_mean", "module.layer3.0.downsample.1.running_var", "module.layer4.0.downsample.0.weight", "module.layer4.0.downsample.1.weight", "module.layer4.0.downsample.1.bias", "module.layer4.0.downsample.1.running_mean", "module.layer4.0.downsample.1.running_var".

**Comment by ahmetgunduz** [comment]
:+1:
