### ISSUE TITLE
I modify run_offline.sh to fit jester dataset, but got precision0.03 recall0.03

### ISSUE THREAD

**Issue by Devincool** [ahmetgunduz/Real-time-GesRec#34]
Hi,
Here's my modified run_offline.sh. If I make some error params, please help to correct. Thanks!

- python offline_test.py \
	--root_path ~/ \
	--video_path /home/ps/NewDisk1/Public_open/Jester/20bn-jester-v1 \
	--annotation_path ~/Codes/Real-time-GesRec/annotation_Jester/jester.json\
	--result_path ~/Codes/Real-time-GesRec/results \
	--pretrain_path Codes/Real-time-GesRec/pretrained_models/jester_resnext_101_RGB_32.pth \
	--dataset jester \
	--sample_duration 32 \
    --learning_rate 0.01 \
    --model resnext \
	--model_depth 101 \
	--batch_size 1 \
	--n_classes 27 \
	--n_finetune_classes 27 \
	--modality RGB
	--n_threads 8 \
	--checkpoint 1 \
	--train_crop random \
	--n_val_samples 1 \
	--test_subset val \
    --n_epochs 100 

[14787/14787]   Time 0.04845 (0.09407)  prec@1 0.03293 prec@5 0.18780   precision 0.00000 (0.03293)     recall 0.00000 (0.03293)
-----Evaluation is finished------
Overall Prec@1 0.03293% Prec@5 0.18780%

**Comment by Devincool** [comment]
I replace pretrain_path by resume_path. Then it work

**Comment by giangnd1808** [comment]
> I replace pretrain_path by resume_path. Then it work

Hi, can you please examine what is the difference between pretrained_path and resume_path? Thank you so much
