### ISSUE TITLE
EgoGesture Dataset is not available

### ISSUE THREAD

**Issue by Fazlik995** [ahmetgunduz/Real-time-GesRec#36]
Hi,

Currently I am learning your code and trying to get your result.

However, I could not download the EgoGesture dataset(author's email is wrong).

Could you please provide another link to download the dataset or any other help.

Thank you!

**Comment by ahmetgunduz** [comment]
Hi, 
Could you please email me the signed [form](http://www.nlpr.ia.ac.cn/iva/yfzhang/datasets/agreementz.txt) : ahmet.gunduz44@gmail.com

**Comment by ahmetgunduz** [comment]
Actually, I am not allowed to share it. If yfzhang@nlpr.ia.ac.cn is wrong, I would suggest you to find a way to access to one of the researchers in the original paper http://www.nlpr.ia.ac.cn/iva/yfzhang/datasets/EgoGesture.pdf

**Comment by Fazlik995** [comment]
I wrote email to yfzhang@nlpr.ia.ac.cn, however i still haven't got any response.

I will write email to other authors.

Thank u:)

**Comment by ZM-J** [comment]
@Fazlik995 Hi! Have you got any response till now?
I need EgoGesture dataset too, but fail to acquire it :( at least `agreement.txt` is not available now

**Comment by nush327** [comment]
even I am not getting ego-gesture datasets. 
I have mailed them but I did not get any response. have anyone got datasets. please help.... @ahmetgunduz  @Fazlik995
