### ISSUE TITLE
How to get the egogesture RGB pretrained model?

### ISSUE THREAD

**Issue by inkzk** [ahmetgunduz/Real-time-GesRec#38]
The google drive files contain only the egogesture_Depth.pth, how to get the RGB model?

**Comment by zhangyuan1994511** [comment]
@ahmetgunduz Hi Author, thanks for sharing your amazing model! I'm very interested in your work, but I only have an RGB camera. Is it easy to share rgb-based models? Thank you very much!

**Comment by ahmetgunduz** [comment]
Hi @zhangyuan1994511 and @inkzk ,

Unfortunately Ido not have the rgb pretrained models. But that is not a big issue. You can use pretrained Depth model to train a RGB model, If you have downloaded egogesture dataset. Just give the path to the pretrained depth model as `pretrained_model` and choose `modality` as 'RGB'. in few epochs, it should converge.

**Comment by zhangyuan1994511** [comment]
@ahmetgunduz OK, I will try it! Thank you for your reply! But i have another question, Is the Depth model and RGB model have the same structure? and this training process is the same as your paper?

**Comment by ahmetgunduz** [comment]
Except some small changes, it is the same as in the paper. 
The model must be RESNEXT 101 in order to be able to use the pretrained model. And except the first convolution filter the rest is the same. This is because of the channel differs for depth and RGB (channel length is 1 and 3 respectively). When you give the right paremeter as I described above, the first convolution will be configured automatically but you must not freeze the model since it needs to learn the first convolution filter as it is randomly initialized.

**Comment by zhangyuan1994511** [comment]
@ahmetgunduz Thank you for your patience. It will help me a lot!

**Comment by zhangyuan1994511** [comment]
@ahmetgunduz Hi, author! Trouble you again! Could you provide the train script on EGO Dataset? I had some problems during training procress.

**Comment by zhangyuan1994511** [comment]
@ahmetgunduz For example, the '--sample_duration' setting, during train detector and classifier on EGO Dataset.

**Comment by zhangyuan1994511** [comment]
@ahmetgunduz For EGO DataSets, During process the dataset, Why distinguish 'all' and 'all_but_None'? which one get the best results as your paper?

**Comment by ahmetgunduz** [comment]
Sorry for the late reply, I did not test the configuration below but it should be fine : 
```bash
#!/bin/bash
python main.py \
	--root_path ~/ \
	--video_path /data/EgoGesture/images \
	--annotation_path ~/Real-time-GesRec/annotation_EgoGesture/egogestureall_but_None.json\
	--result_path ~/Real-time-GesRec/results \
	--pretrain_path MyRes3D-Ahmet/report/egogesture_resnext_101_Depth_32.pth \
	--dataset egogesture \
	--sample_duration 32 \
    --learning_rate 0.01 \
    --model resnetl \
	--model_depth 10 \
	--resnet_shortcut A \
	--batch_size 8 \
	--n_classes 83 \
	---n_finetune_classes 83 \
	--n_threads 16 \
	--checkpoint 1 \
	--modality RGB \
	--train_crop random \
	--n_val_samples 1 \
	--test_subset test \
     --n_epochs 100 \
```

"all" means 83 gestures + 1 NO_GESTURE class, "all_but_None" meas only 83 gesture classes.
