### ISSUE TITLE
Any online test example code for jester data?

### ISSUE THREAD

**Issue by inkzk** [ahmetgunduz/Real-time-GesRec#39]

**Comment by ahmetgunduz** [comment]
Unfortunately no because jester does not provide labels for no_gesture class, which means, no detector can be trained.

**Comment by jashshah** [comment]
Hi @ahmetgunduz I'm a little confused. While going through the information around the Jester dataset (https://20bn.com/datasets/jester) there seems to be a `No gesture` class. Can this be used or are we missing something?

**Comment by ahmetgunduz** [comment]
Hi @jashshah , may bad you are right. You can use this `no gesture`   class and combine all other classes to train a detector model and later classifier.

**Comment by guptapersonal** [comment]
If I download the pre trained model, can I run it directly to experiment  ?

I tried run online or offline n got the following in both cases. 
I just want to use pretained model .. please suggest 

THCudaCheck FAIL file=..\aten\src\THC\THCGeneral.cpp line=74 error=35 : CUDA driver version is insufficient for CUDA runtime version
Traceback (most recent call last):
  File "main.py", line 51, in <module>
    model, parameters = generate_model(opt)
  File "C:\data\h\Real-time-GesRec-master\model.py", line 133, in generate_model
    model = model.cuda()
  File "C:\Users\v\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 258, in cuda
    return self._apply(lambda t: t.cuda(device))
  File "C:\Users\v\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 185, in _apply
    module._apply(fn)
  File "C:\Users\v\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 191, in _apply
    param.data = fn(param.data)
  File "C:\Users\v\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 258, in <lambda>
    return self._apply(lambda t: t.cuda(device))
RuntimeError: cuda runtime error (35) : CUDA driver version is insufficient for CUDA runtime version at ..\aten\src\THC\THCGeneral.cpp:74

**Comment by guptapersonal** [comment]
> Hi @ahmetgunduz
> 
> If I download the pre trained model, can I run it directly to experiment ?
> 
> I tried run online or offline n got the following in both cases.
> I just want to use pretained model .. please suggest
> 
> THCudaCheck FAIL file=..\aten\src\THC\THCGeneral.cpp line=74 error=35 : CUDA driver version is insufficient for CUDA runtime version
> Traceback (most recent call last):
> File "main.py", line 51, in
> model, parameters = generate_model(opt)
> File "C:\data\h\Real-time-GesRec-master\model.py", line 133, in generate_model
> model = model.cuda()
> File "C:\Users\v\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 258, in cuda
> return self._apply(lambda t: t.cuda(device))
> File "C:\Users\v\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 185, in _apply
> module._apply(fn)
> File "C:\Users\v\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 191, in _apply
> param.data = fn(param.data)
> File "C:\Users\v\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 258, in
> return self._apply(lambda t: t.cuda(device))
> RuntimeError: cuda runtime error (35) : CUDA driver version is insufficient for CUDA runtime version at ..\aten\src\THC\THCGeneral.cpp:74

any help here please @ahmetgunduz

**Comment by xiaowen11** [comment]
Thank you very much for your patience

When I execute: sh run-jetster.sh Instruction,  training Jester data set has obtained gesture recognition model.  I want to use this model to test the real-time images taken from the camera.
And How should I build a  run_online_video_jester.sh file to test the model as well as the   run_online_video_egogesture file?
