### ISSUE TITLE
opts

### ISSUE THREAD

**Issue by nainadhingra2012** [ahmetgunduz/Real-time-GesRec#4]
Hey Ahmet,

I am trying to replicate your work. I am having problems in dataloader (probably). I haven't changed anything in your code except for the paths and few minor changes for which I was getting errors.

My opt looks like:

annotation_path='/home/ndhingra/Real-time-GesRec/Real-time-GesRec/annotation_EgoGesture/egogestureall.json', arch='resnet-10', batch_size=128, begin_epoch=1, checkpoint=10, crop_position_in_test='c', dampening=0.9, dataset='egogesture', ft_begin_index=0, initial_scale=1.0, learning_rate=0.1, lr_patience=10, lr_steps=[10, 25, 50, 80, 100], manual_seed=1, mean=[114.7748, 107.7354, 99.475], mean_dataset='activitynet', modality='RGB', model='resnet', model_depth=10, momentum=0.9, n_classes=400, n_epochs=200, n_finetune_classes=400, n_scales=5, n_threads=4, n_val_samples=3, nesterov=False, no_cuda=False, no_hflip=False, no_mean_norm=False, no_softmax_in_test=False, no_train=False, no_val=False, norm_value=1, optimizer='sgd', pretrain_path='', resnet_shortcut='B', resnext_cardinality=32, result_path='/home/ndhingra/Real-time-GesRec/Real-time-GesRec/results', resume_path='', root_path='/home/ndhingra/Real-time-GesRec/Real-time-GesRec', root_video_path='/media/storage/ndhingra/EgoGesture', sample_duration=16, sample_size=112, scale_in_test=1.0, scale_step=0.84089641525, scales=[1.0, 0.84089641525, 0.7071067811803005, 0.5946035574934808, 0.4999999999911653], std=[38.7568578, 37.88248729, 40.02898126], std_norm=False, store_name='model', test=False, test_subset='val', train_crop='corner', train_validate=False, video_path='/home/ndhingra/Real-time-GesRec/Real-time-GesRec/images', weight_decay=0.001, weighted=False, wide_resnet_k=2)

I get error in main.py

 train_loader = torch.utils.data.DataLoader(
            training_data,
            batch_size=opt.batch_size,
            shuffle=True,
            num_workers=opt.n_threads,
            pin_memory=True)

i.e., 

ValueError: num_samples should be a positive integeral value, but got num_samples=0

Can you suggest what changes do I have to make? If possible can you also upload opts.py which you used for egogesture dataset. Since I haven't made any changes to your code, I expect it to work as it worked for you.

**Comment by nainadhingra2012** [comment]
Hey, thanks, I found a bug.

Cheers

**Comment by ahmetgunduz** [comment]
Hey Naina,
It seems it does not find the paths correctly. It may be because of root_path, which is preappended to all specified path parameters. For example is it "/home/ndhingra/..." or "~/home/ndhingra/..". For this case root_path = '~' needs to be provided. 


> Hey, thanks, I found a bug.
> 
> Cheers

Were you able to fix the problem already?

**Comment by nainadhingra2012** [comment]
Hi Ahmet,

Yes, I was able to fix the problem. Everything works fine now. 

But, I did have to make changes in utils.py for converting it to cpu tensor
$otherwise, I got an error saying " can't convert CUDA tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first."

    #return  precision_score(targets.view(-1), pred.view(-1), average = 'macro')   #old
    return  precision_score(targets.view(-1).cpu(), pred.view(-1).cpu(), average = 'macro') #modified

But, I also get a warning after this that : 
" UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples." and
"UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples."

I am considering that you would have used GPU too, did you use some other solution for it?

**Comment by ahmetgunduz** [comment]
Great! I am closing the issue then. 

P.S. The cuda tensor error must be an issue with sklearn version I think. But good that you solved. The warning you mentioned is not sth important. It happens when there is no prediction for each classes.

**Comment by nainadhingra2012** [comment]
Thanks a lot!
