### ISSUE TITLE
Running realtime classifiaction on an RGB camera

### ISSUE THREAD

**Issue by aryankoul** [ahmetgunduz/Real-time-GesRec#44]
Can you please provide steps to run the real time classification (online_test.py) on a RGB camera such as a normal laptop webcam.

**Comment by ahmetgunduz** [comment]
please see https://github.com/ahmetgunduz/Real-time-GesRec/issues/17#issuecomment-492430596 a

**Comment by aryankoul** [comment]
Thanks.
Also, the models you have provided are for depth images. Do you have pretrained model for color images for nvgesture or egogesture?

**Comment by ahmetgunduz** [comment]
Unfortunately, I do not have them anymore.

**Comment by aryankoul** [comment]
Also, i had a query. Can i use this depth model to detect gesture from normal laptop webcam?

**Comment by ahmetgunduz** [comment]
You need to retrain models for RGB images by using depth models as pretrained model. Please check README file for how to initiate a training.
