### ISSUE TITLE
how upzip nvGesture dataset, i use 7za e datafilename

### ISSUE THREAD

**Issue by LLLLLLoki** [ahmetgunduz/Real-time-GesRec#45]
7-Zip (A) [64] 9.20  Copyright (c) 1999-2010 Igor Pavlov  2010-11-18
p7zip Version 9.20 (locale=en_US.UTF-8,Utf16=on,HugeFiles=on,72 CPUs)

Processing archive: /home/lxj/Gesture_recognition/data/nvGesture/nvGesture_v1.7z.001

Error: E_FAIL

**Comment by ahmetgunduz** [comment]
this is irrelevant to the repo.
