### ISSUE TITLE
Unable to extract Jester datasets

### ISSUE THREAD

**Issue by Agrawalchitranshu** [ahmetgunduz/Real-time-GesRec#52]
Hi,
I am getting an error while extracting the Jester dataset files except 20bn-jester-v1-00 data file, while other files are giving the error. And when I checked the type of the data files, So what I observed it the file type of 20bn-jester-v1-00 is different from the other files. I am attching the screenshot of the error I am gettting which also includes the file types, please help if you have also resolved the same issue.
![Screenshot from 2020-04-13 16-22-38](https://user-images.githubusercontent.com/21341582/79115751-5311b780-7da4-11ea-99ac-d11905586ac0.png)

**Comment by ahmetgunduz** [comment]
Unfortunately, I did not have such a problem. If you can email to jester dataset provider, they may resolve the problem.

**Comment by Agrawalchitranshu** [comment]
Thanks, I have emailed them regarding the same, wating for them to answer.
