### ISSUE TITLE
Testing on real-time RGB video using jester Pretrained model 

### ISSUE THREAD

**Issue by lavpreet** [ahmetgunduz/Real-time-GesRec#55]
I am trying to understand your code. I have understood that for other datasets there is two models detector and classifier. I only have jester dataset available with me. And for that we only one model. 

Can you please tell me How can we do real time detection RGB camera video without detetctor?
And can we recognize gesture with jester model?
or which model of other datasets can be used for same?

**Comment by ahmetgunduz** [comment]
I would train a detector for Jester if I were you. It would be easier. Otherwise, you need to modify online_test.py if you wanna run the code without a detector.

**Comment by lavpreet** [comment]
Thank for replying and I have some questions,

Won't I need binary annotations for every frame of dataset as in ego dataset I can clearly see a binary annotations. Did you created that or it was already provided or you run some code for that.

If  you have  run jester model for any other video than public datasets. you have written any code for without detector please share.

And one more thing how much time it takes to get ego dataset.

**Comment by ahmetgunduz** [comment]
Dear @lavpreet , 
1) You need to prepare an annotation file for binary case. Under `utils` folder, you would see the example codes for egogesture and nvgesture datasets. You need to use `no_gesture` class of the jester dataset. The mapping would be as following: `no_gesture->0`, `all other classes->1`. 
2) I used jester only for pretraining purposes only. All of the pretrained models can be found in the links provided in README.
