### ISSUE TITLE
trainning Detetor and Classifier Model 

### ISSUE THREAD

**Issue by zh199110** [ahmetgunduz/Real-time-GesRec#56]
Hi ,
   I want to know how to train the Detector model and classifier model ,can you show me the  scripts parameters  of setting ? Thank you very much !

**Comment by ahmetgunduz** [comment]
Only difference between detector and Classifier is the `n_classes_fine_tune` parameter. And you need to select proper annotation json files. As one is binary with two classes and the latter is with multiple classes.
