### ISSUE TITLE
issues by online testing pretrained model

### ISSUE THREAD

**Issue by Stancoo** [ahmetgunduz/Real-time-GesRec#57]
Dear Ahmet,

Thanks for sharing your codes.  
I'm trying to get some idea of how good are the pretrained models.
I'm running: 

_. run_online.sh_

which in my case looks like:

python3 online_test.py \
        --root_path /home/sc/WORK/python/gesture_pytorch/Real-time-GesRec \
        --video_path /data2/EgoGesture/images \
        --annotation_path annotation_EgoGesture/egogestureall.json \
        --resume_path_det ../models/egogesture_resnetl_10_Depth_8.pth \
        --resume_path_clf ../models/egogesture_resnext_101_Depth_32.pth  \
        --result_path results \
        --dataset egogesture    \
        --sample_duration_det 8 \
        --sample_duration_clf 32 \
        --model_det resnetl \
        --model_clf resnext \
        --model_depth_det 10 \
        --model_depth_clf 101 \
        --resnet_shortcut_det A \
        --resnet_shortcut_clf B \
        --batch_size 1 \
        --n_classes_det 2 \
        --n_finetune_classes_det 2 \
        --n_classes_clf 83 \
        --n_finetune_classes_clf 83 \
        --n_threads 16 \
        --checkpoint 1 \
        --modality_det Depth \
        --modality_clf Depth \
        --n_val_samples 1 \
        --train_crop random \
        --test_subset test  \
        --det_strategy median \
        --det_queue_size 4 \
        --det_counter 2 \
        --clf_strategy median \
        --clf_queue_size 16 \
        --clf_threshold_pre 0.6 \
        --clf_threshold_final 0.15 \
        --stride_len 1 \
        #--no_cuda \

and stack with the following error:

_loading checkpoint /home/sc/WORK/python/gesture_pytorch/Real-time-GesRec/../models/egogesture_resnetl_10_Depth_8.pth
Traceback (most recent call last):
  File "online_test.py", line 152, in <module>
    detector, classifier = load_models(opt)
  File "online_test.py", line 95, in load_models
    detector.load_state_dict(checkpoint['state_dict'])
  File "/home/sc/venv/work/lib/python3.8/site-packages/torch/nn/modules/module.py", line 846, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for DataParallel:
        size mismatch for module.conv1.weight: copying a param with shape torch.Size([16, 1, 7, 7, 7]) from checkpoint, the shape in current model is torch.Size([16, 3, 7, 7, 7])._

Could you please give a hint on this issue? Thanks a lot!

**Comment by ahmetgunduz** [comment]
It looks like the model's modality is not set properly. This is a bug I believe.  Could you pull the project and check again? I have submitted a code change.

**Comment by kinfeparty** [comment]
> It looks like the model's modality is not set properly. This is a bug I believe. Could you pull the project and check again? I have submitted a code change.

Hello! My run-online.sh code is similar to him. and is similar to run-online.sh 
I use the newest project  , but error exist.

RuntimeError: Error(s) in loading state_dict for ResNetL:
        Missing key(s) in state_dict: "conv1.weight", "bn1.weight", "bn1.bias", "bn1.running_mean", "bn1.running_var", "layer1.0.conv1.weight", "layer1.0.bn1.weight", "layer1.0.bn1.bias", "layer1.0.bn1.r$
nning_mean", "layer1.0.bn1.running_var", "layer1.0.conv2.weight", "layer1.0.bn2.weight", "layer1.0.bn2.bias", "layer1.0.bn2.running_mean", "layer1.0.bn2.running_var", "layer2.0.conv1.weight", "layer2.0.bn
1.weight", "layer2.0.bn1.bias", "layer2.0.bn1.running_mean", "layer2.0.bn1.running_var", "layer2.0.conv2.weight", "layer2.0.bn2.weight", "layer2.0.bn2.bias", "layer2.0.bn2.running_mean", "layer2.0.bn2.run
ning_var", "layer3.0.conv1.weight", "layer3.0.bn1.weight", "layer3.0.bn1.bias", "layer3.0.bn1.running_m
