### ISSUE TITLE
Testing the pretrained module with cpu issue

### ISSUE THREAD

**Issue by baga1072** [ahmetgunduz/Real-time-GesRec#58]
I have an issue with offline_test.py, downsample by default is 1. 
This is the error that shows in the terminal.
`File "offline_test.py", line 106, in <module> `
`temporal_transform = TemporalCenterCrop(opt.sample_duration)`
`TypeError: __init__() missing 1 required positional argument: 'downsample'`

**Comment by ahmetgunduz** [comment]
@baga1072  Could you please pull the repo again and check it?
