### ISSUE TITLE
Loading pre-trained model

### ISSUE THREAD

**Issue by nickSteeleStanfordAI** [ahmetgunduz/Real-time-GesRec#59]
Hi,
I have this issue when loading a pre-trained model training on CPU.
Best,
Nick
<img width="886" alt="Screen Shot 2020-05-15 at 9 35 37 PM" src="https://user-images.githubusercontent.com/48195320/82134810-ab2b4780-97b0-11ea-8dfe-e216a534d91f.png">

**Comment by ahmetgunduz** [comment]
Hey Nick, please check this : https://discuss.pytorch.org/t/on-a-cpu-device-how-to-load-checkpoint-saved-on-gpu-device/349

**Comment by nickSteeleStanfordAI** [comment]
Great, thank you.  Will try that

**Comment by ahmetgunduz** [comment]
Hi @nickSteeleStanfordAI , the codabase is updated. Could you please pull and retry?
