### ISSUE TITLE
adjust_learning_rate in main.py is not defined

### ISSUE THREAD

**Issue by JuliaJiaYou** [ahmetgunduz/Real-time-GesRec#61]
Hi there, I try to run this code but get the error, "adjust_learning_rate(optimizer, i, opt)" in main.py is not defined (at line 155, main.py)
I wonder where is the definition for it? Seems this is necessary. I tried to delete it and get the assertion error while running. 
In addition, I use nvGestures, but seems there are not code to convert the .avi to .jpg images. I add one by my own.

**Comment by ahmetgunduz** [comment]
There seems to be deleted in the latest merge. I will fix this soonest. For now you can go and check the commit  a5c01304c580654a8989c81f35ded71c5ab57ff1  deleted it by mistake. Thanks for letting me to know.

**Comment by JuliaJiaYou** [comment]
The link you provide is very useful!!! Thanks for your help!

**Comment by ahmetgunduz** [comment]
The codabase is updated. It is now in `utils.pp`
