### ISSUE TITLE
How to train the model by myself, not use pre-trained model

### ISSUE THREAD

**Issue by JuliaJiaYou** [ahmetgunduz/Real-time-GesRec#62]
Hi there, I wonder how to train the model by myself. Should I uncomment line 91 to 100 in "train.py", to save .pth files?

**Comment by ahmetgunduz** [comment]
If you do not specify `--pretrained_path`, it should be fine. And if you do not want to save your own models then you can uncomment those lines. But I would not recommend that you will lose your trained models.
