### ISSUE TITLE
Download the pretrained model

### ISSUE THREAD

**Issue by kinfeparty** [ahmetgunduz/Real-time-GesRec#63]
Hello! Thanks for you great work!
I want to download your pretrained model, but I found the two links  could not work.    ERR_TIMED_OUT

 I've try the vpn but still couldn't enter the website.
May you check the link?

**Comment by ahmetgunduz** [comment]
The links are working for me. There must be an error with your internet connection.

**Comment by kinfeparty** [comment]
@ahmetgunduz   thank you , something wrong with my VPN
