### ISSUE TITLE
Github navigation disappear

### ISSUE THREAD

**Issue by JuliaJiaYou** [ahmetgunduz/Real-time-GesRec#67]
Hi! Thanks for your kind sharing and modification! After I find you make modification, I came immediately to learn the difference! 
But I find that navigation of github functions disappear. I means, several weeks ago, when I want to know better about a function or a variable, I just put mouse  to it and github page can navigate me. But now navigation disappears. 
Are there any solutions? 
I am new to github, so I am not sure where this problem come from. Could you please give me some hint?

**Comment by ahmetgunduz** [comment]
It works for me. Strange. Wht not use pycharm, vs code or any other ide?

**Comment by JuliaJiaYou** [comment]
I just open on the website and the navigation disappear. 
I will try pycharm! Thanks!
