### ISSUE TITLE
about offline_test

### ISSUE THREAD

**Issue by MDWW** [ahmetgunduz/Real-time-GesRec#68]
Hi, thank you for sharing the code. while I try to run offline_test.py I got an error , and I found the opts.py doesn't contain a definition of parse_opts_offline(), which is required in the offline_test.py.
Besides, i wonder do i need to download the whole database to run the online/offline_test.py?

**Comment by ahmetgunduz** [comment]
Could you please check again with the latest commit? Also you do not need to download all the dataset but need to make sure that code will not give any exception since I used the all database.
