### ISSUE TITLE
hi,guy,can you tell me is this project can be running iin windows?thanks !

### ISSUE THREAD

**Issue by luchen828** [ahmetgunduz/Real-time-GesRec#73]

**Comment by luchen828** [comment]
hope you can reply me if you see this question.waitiing for you reply.thank you very much.

**Comment by ahmetgunduz** [comment]
it is not different than running another python code in windows.

**Comment by luchen828** [comment]
thank you very much!




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Ahmet Gündüz"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月13日(星期六) 下午5:04
收件人:&nbsp;"ahmetgunduz/Real-time-GesRec"<Real-time-GesRec@noreply.github.com&gt;;
抄送:&nbsp;"122"<787940575@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [ahmetgunduz/Real-time-GesRec] hi,guy,can you tell me is this project can be running iin windows?thanks ! (#73)





 
it is not different than running another python code in windows.
