### ISSUE TITLE
what is input data for training detector?

### ISSUE THREAD

**Issue by learningsteady0J0** [ahmetgunduz/Real-time-GesRec#75]
Hi! 

I read your paper well. I will use this to recognize Korean sign language.

I don't know if I didn't find it, What input data did you put into the detector?

I think that EX)

gesture  :  Use all 8 frames starting within the dataset.

no_gesture :  i don't know... 

Thank you so much for your good experiment!

**Comment by ahmetgunduz** [comment]
Hi @learningsteady0J0 , the data is frames of videos. You can use different modalities (Depth, RGB or RGB-D) the same way in the classifier. The only difference between classifier and dedector is the number of classes. The detector is a binary classifier.

**Comment by learningsteady0J0** [comment]
> between
Thank you for your reply! I don't think I got it right.

If class is up to 1,2,3...9 in the dataset A,
'classifier' use class 1,2,3...9 
but 'detector' use class gesture(all 1 to 9) and no gesture.

Is that what I thought?
So how did you collect the dataset for 'no gesture'?

I don't know if I wrote it well because I'm not good at English.
Thank you so much!

**Comment by ahmetgunduz** [comment]
`If class is up to 1,2,3...9 in the dataset A,
'classifier' use class 1,2,3...9
but 'detector' use class gesture(all 1 to 9) and no gesture`
That is right! 

Egogesture, NVGesture and Jester datasets has  either has "no gesture" class or I extracted the no gesture parts. If you do notha have "no gesture" classes in your dataset, you can train a detector using a similar dataset with no gesture classes.

**Comment by learningsteady0J0** [comment]
You made everything clear.

Thank you veryyyyyyy much!

I hope everything you do goes well!
